### ISSUE TITLE
[RFE] TODO list for turning this into a Flatcar App

### ISSUE THREAD

**Issue by t-lo** [flatcar/jitsi-server#3]
## Current situation

Automation largely works but is based on Ubuntu, so the OS won't self-update after provisioning. Also, there's no way to provision w/o manual interaction with the instance afterwards.

## Impact

Provisioning needs manual attention.

## Ideal future situation

Deployment is fully configurable before provisioning, provisioning is automated for Flatcar. OS and Sysext update concepts are integrated and allow for customisation (maintenance windows).

## Implementation options

- [x] Basic automation for provisioning on Flatcar
    - [x] Automation uses system `jitsi` system user, `/opt/jitsi` exclusively.
    - [x] Automation is self-contained, i.e. does not need to check out this repo on the node
    - [ ] Automation cleans up installer (this repo) after successful installation.
- [x] Automation gaps are closed
    - [x] Set-up script identifies host IP address and passes it to Jitsi config
    - [x] Set-up script waits for hostname to resolve to host IP before starting installation.
           This allows orchestration to create a DNS entry for the freshly deployed host w/o race condition with Jitsi's ACME cert request.
- [x] Automation is customisable, uses templates / env vars
    - [x] hostname and letsencrypt email
    - [x] optionally the Jitsi version to deploy
    - [x] optionally user and password (default to `jitsi` and auto-generation)
    - [x] optionally banner, logo, and watermark (skip if not present)

**Comment by t-lo** [comment]
Mostly done, closing.
